# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: wenjiao-test

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      pip install pylint==2.12.1
      # tf_utils.util will import some deps installed by tensorflow
      pip install intel-tensorflow
      python -m pylint -f json --disable=R,C,W,E1129 --enable=line-too-long --max-line-length=120 --extension-pkg-whitelist=numpy --ignored-classes=TensorProto,NodeProto --ignored-modules=tensorflow,torch,torch.quantization,torch.tensor,torchvision,mxnet,onnx,onnxruntime ./neural_compressor > ${WORKSPACE}/lpot-pylint.json
      exit_code=$?
      if [ ${exit_code} -ne 0 ] ; then
          echo "PyLint exited with non-zero exit code."; exit 1
      fi
      exit 0
