# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  docker-agent

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install pylint==2.12.1'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'pip install intel-tensorflow'

